### ISSUE TITLE
Patching on GNU/Linux?

### ISSUE THREAD

**Issue by vanfanel** [dave18/BubNext#4]
Hi!

I am trying to run BBNextPatch on GNU/Linux using WINE like this:
`wine BBNextPatch.exe BUBNEXT.nex`

The needed ROMs are of course in place, in the same directory as the executable.

However, it stays there seemingly forever, the patching process never ends.

So, is there a way to patch this on GNU/Linux, please? I don't have (and don't want or plan to have) a Windows machine around me.

**Comment by dave18** [comment]
Hi

I've just tried on a new Ubuntu install running in VirtualBox and it seems fine.  Used command line wine /fullpathtofile/BBNextPatch.exe BUBNEXT.NEX

Maybe try with a fresh install?

![image](https://github.com/dave18/BubNext/assets/1486501/49e89370-c017-4443-8e44-3109a3378745)

**Comment by vanfanel** [comment]
@dave18 Thanks Dave! I deleted the ~/.wine directory, let WINE rebuild it's configuration again, and it worked fine!

Closing this, sorry to annoy you! This is such an awesome conversion!
